name: Deploy Smartify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/smartify
            git reset --hard
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            docker image prune -f
